on:
  push:
    tags:
      - "*"

name: Build android apk

jobs:
  build-dev:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build app
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release --target-platform android-arm
      - name: Release app
        uses: ncipollo/release-action@v1
        with:
          artifacts: "
          build/app/outputs/apk/release/app-release.apk
          "
          token: ${{ secrets.GITHUB_TOKEN }}
